// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQgjOWKSee126QXWDCwsy5aE_Q0E5MR5U',
    appId: '1:143822341549:web:7bd1bd34749195a7b60d24',
    messagingSenderId: '143822341549',
    projectId: 'quest-rooms-fb316',
    authDomain: 'quest-rooms-fb316.firebaseapp.com',
    storageBucket: 'quest-rooms-fb316.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDelxHc6w0TL0rFK5fh3P7mEJTzI7c5Y6w',
    appId: '1:143822341549:android:b7ee90ed8ac76ed2b60d24',
    messagingSenderId: '143822341549',
    projectId: 'quest-rooms-fb316',
    storageBucket: 'quest-rooms-fb316.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQgjOWKSee126QXWDCwsy5aE_Q0E5MR5U',
    appId: '1:143822341549:web:79e0c493014b32abb60d24',
    messagingSenderId: '143822341549',
    projectId: 'quest-rooms-fb316',
    authDomain: 'quest-rooms-fb316.firebaseapp.com',
    storageBucket: 'quest-rooms-fb316.firebasestorage.app',
  );
}
